// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpcbmpsqeklrcdwjmmad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwY2JtcHNxZWtscmNkd2ptbWFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzA3NTcsImV4cCI6MjA3MjMwNjc1N30.OozAq90LeHSdnl9JaiyeZfdOiPonKXjFl3jQwC7uZVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});